### PR TITLE
enhancing json3 for traces

### PR DESCRIPTION
**Pull request by hhaensel**
This is a PR referring to #88

### CODE REVIEW

**Comment by hhaensel** [comment]
Maybe we should also include AbstractShape?

**Comment by sglyon** [comment]
Maybe it makes sense to use `HasFields`?

https://github.com/sglyon/PlotlyBase.jl/blob/ed4965626439fb81d2fb860b1a96cf61001664fc/src/traces_layouts.jl#L170

**Comment by sglyon** [comment]
FYI, this is basically how we handle things for JSON.jl

https://github.com/sglyon/PlotlyBase.jl/blob/b5119777a997367188c83d09924cfbb8f54130bb/src/json.jl#L4

**Comment by hhaensel** [comment]
That was a good hint 😃

**Comment by hhaensel** [comment]
I've added another PR to accomplish the same definitions for PlotConfig as for HasFields

**Pull request merged**
