### PR TITLE
fix json for Layout and Colorant, add tests

### PR DESCRIPTION
**Pull request by hhaensel**
This is a possible follow up with some corrections to #102

### CODE REVIEW

**Comment by hhaensel** [comment]
@sglyon 
Does this PR sound reasonable to you?

**Comment by alyst** [comment]
Also see the related #107

**Comment by hhaensel** [comment]
Hi @sglyon ,
would you find the time to look over this PR?
It's not only about making Colors a direct dependency but also about correct rendering of transparent colors.

**Comment by sglyon** [comment]
Thanks for the ping! Looks nice

**Pull request merged**
