### PR TITLE
Missing Dependency

### PR DESCRIPTION
**Pull request by Nosferican**

### CODE REVIEW

**Comment by sglyon** [comment]
Thanks, but I believe this is not necessary.

Distributions-specific code is loaded using Requires.jl only after PlotlyBase and Distributions are both loaded. See here: https://github.com/sglyon/PlotlyBase.jl/blob/d8bd587d4832d0cdafb2239afa16ed116e432869/src/PlotlyBase.jl#L115

Please re-open if I misunderstood something

**Comment by Nosferican** [comment]
Not sure the exact behavior, but when I have them both loaded I get the very annoying warning. Is there a way to handle the warning?

**Comment by sglyon** [comment]
So I did recently make changes that should remove that error.

Will you check out `PlotlyBase#master`, try it one more time, and let me know if it works?

**Comment by Nosferican** [comment]
Seems to be fixed now on master.

**Comment by sglyon** [comment]
OK cool, I'll publish a release soon that includes that fix.

Thanks for following up

**Pull request closed without merging**
