### PR TITLE
Use `--single-process` flag to try fix MacOS issues.

### PR DESCRIPTION
**Pull request by MichaelHatherly**
This might help, have tested locally on a macos vm, but less see what ci says... 🤞🏻

### CODE REVIEW

**Comment by giordano** [comment]
:tada:

**Comment by MichaelHatherly** [comment]
Looks like that fixed the Mac issue @sglyon, if you're happy with it then could we get a new patch release with this fix?

**Comment by sglyon** [comment]
Wow that's awesome! Thank you for finding a fix so quickly. 

Do you know if there are any downsides to using this option when not running on Mac?

**Comment by MichaelHatherly** [comment]
Here's the details on the options: https://www.chromium.org/developers/design-documents/process-models

`--single-process` is the only one that worked on mac out of the 4 choices, the caveats about it are also slightly worrying. We can go with only using `--single-process` on `isapple` instead since the default doesn't appear to affect other platforms.

**Comment by sglyon** [comment]
That sounds great, Thanks @MichaelHatherly

**Pull request merged**
