### PR TITLE
bump `DocStringExtensions`: fix `Plots` ci

### PR DESCRIPTION
**Pull request by t-bltg**
Failing ci jobs, e.g. https://github.com/JuliaPlots/Plots.jl/runs/8048912406?check_suite_focus=true.

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
we'd need to have that backported to 0.7

**Comment by t-bltg** [comment]
@sglyon, can you backport this PR to a `release-0.7` asap, since we don't have write access on this repo ?

**Comment by sglyon** [comment]
@t-bltg not sure what you want me to do here? I don't think I have a release-0.7 branch (or plans to support pre Julia 1.0)

**Comment by t-bltg** [comment]
1. we have a broken Plots ci because of `Plotly` chain dependencies;
2. we can't bump `PlotlyBase` to `0.8` [comment](https://github.com/JuliaPlots/Plots.jl/pull/4319#issuecomment-1229210796).

What can we do then, apart from backporting this PR to a `0.7` branch ?

**Comment by BeastyBlacksmith** [comment]
> I don't think I have a release-0.7 branch (or plans to support pre Julia 1.0)

We meant PlotlyBase 0.7, not julia 0.7. What we need is a branch from the last 0.7.x release to which we can also merge this changes to release a version 0.7.x+1 of PlotlyBase

**Comment by sglyon** [comment]
Thanks!

https://github.com/JuliaRegistries/General/pull/67500

**Pull request merged**
