### PR TITLE
add margin to each style and update (gadfly_dark)

### PR DESCRIPTION
**Pull request by asbisen**
To fix the issue described in #15

### CODE REVIEW

**Comment by sglyon** [comment]
Thanks for submitting this. I think that we might want to take advantage of the `layout.yaxis.automargin`, `layout.xaxis.automargin`, and `layout.autosize` settings here. if we set all of them to `true` plotly _should_ dynamically compute the size of the margin so that tick and axis labels have enough room.

Are you willing to give it a shot?

**Comment by asbisen** [comment]
I checked, `autosize` and `axis.automargin` does not affects the clipped title.

screen shot 2018-11-03 at 11 50 07 pm

**Comment by sglyon** [comment]
Ahh yes. How about we use those options and only a top margin?

I’d like to not force margin into plots if possible to avoid.

**Comment by asbisen** [comment]
made the changes only adding top margin. Also kept `automargin` and `autosize` in place, I thought is a good default.

**Comment by sglyon** [comment]
Excellent, you did exactly what I was thinking. 

Thanks for addressing this

**Pull request merged**
