### PR TITLE
Use `Kaleido_jll` for Kaleido

### PR DESCRIPTION
**Pull request by giordano**
CC: @sglyon

### CODE REVIEW

**Comment by sglyon** [comment]
trying to get CI to work for mac....

I'll grab my machine and see if it works for me locally

**Comment by andreasnoack** [comment]
Bump. It would be great to get this one in since it's causing some issues for us when we want to relocate an application based on this package.

**Comment by MichaelHatherly** [comment]
The `kaleido` call in `_start_kaleido_process` is failing for me on mac with the following:

```
julia> Kaleido_jll.kaleido() do bin
           run(`$bin plotly --disable-gpu`)
       end
[0326/093300.913531:FATAL:double_fork_and_exec.cc(126)] execvp /Users/mike/.julia/artifacts/704a8a26764bb0e8e719d78ef2f95eaab6ca2dbd/bin/Helpers/chrome_crashpad_handler: No such file or directory (2)
[0326/093300.914519:ERROR:file_io.cc(89)] ReadExactly: expected 8, observed 0
[0326/093300.916268:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale en-US
{"code": 0, "message": "Success", "result": null, "version": ""}
[0326/093301.214846:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale en-US
[0326/093301.217549:ERROR:network_service_instance_impl.cc(262)] Network service crashed, restarting service.
[0326/093301.217603:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale en-US
[0326/093301.241694:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale en-US
[0326/093301.295221:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale en-US
[0326/093301.475566:ERROR:network_service_instance_impl.cc(262)] Network service crashed, restarting service.
[0326/093301.545798:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale en-US
[0326/093301.548514:ERROR:network_service_instance_impl.cc(262)] Network service crashed, restarting service.
[0326/093301.626190:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale en-US
[continues indefinitely...]
```

**Comment by giordano** [comment]
> The kaleido call in _start_kaleido_process is failing for me on mac with the following:

Does it work on `master` or latest stable version?  Tests don't seem to have ever worked on macOS

**Comment by MichaelHatherly** [comment]
`0.5` is fine, `master` looks to be failing with a similar error.

**Comment by giordano** [comment]
> `master` looks to be failing with a similar error.

That's not a regression then :slightly_smiling_face:

**Comment by sglyon** [comment]
I'm willing to merge, but would love some help fixing things up on OSX. 

Unfortunately I'm stretched a bit thin right now and don't have time to dig in

**Comment by MichaelHatherly** [comment]
Might be worth seeing if https://github.com/plotly/Kaleido/releases/tag/v0.2.1 works any better.

**Comment by giordano** [comment]
@MichaelHatherly can you try to directly run `kaleido` in https://github.com/plotly/Kaleido/releases/download/v0.1.0/kaleido_mac.zip, and see if you can reproduce the same error?  That's what we're using

**Comment by MichaelHatherly** [comment]
Both that one and `0.2.1` give the same issues. Just testing out some different flags now to the binary, which _might_ help...

**Comment by MichaelHatherly** [comment]
See #44.

**Pull request merged**
