### PR TITLE
First pass at updating API for allowing animations

### PR DESCRIPTION
**Pull request by nicrummel**
The JavaScript api allows for 'animation' mode which requires the plot json to have a frames field. The Julia code that connects to this api can be extended minimally to accommodate this functionality. This is my first time contributing here, so let me know if I missed the mark stylistically or otherwise, and I hope this helps the community.

### CODE REVIEW

**Comment by sglyon** [comment]
Oh and stylistically and all other ways you were spot on. Thank you! Happy to have you on board as a contributor

**Comment by nicrummel** [comment]
Thanks Dr. Lyon. I added tests for PlotlyFrame. I honestly for some of the tests, I copied code from the existing tests. I hope this satisfies what you were looking for.

**Comment by sglyon** [comment]
After a quick glance this looks great. I'll try to review this week!

**Comment by sglyon** [comment]
Merged now, thank you!

**Comment by nicrummel** [comment]
Awesome! Thank you Dr. Lyon.

**Pull request merged**
