### PR TITLE
migrate to weakdeps

### PR DESCRIPTION
**Pull request by sjkelly**
This adds support for the weakdeps feature on Julia 1.9 and later.

### CODE REVIEW

**Comment by hhaensel** [comment]
Just reinvented the wheel ...
I should have had a look here first. I arrived at very much the same solution.
Two things:
- there's a `PlotlyBase.` missing in front of _json_lower in ColorsExt
- JSON2Ext is missing; is that by purpose?

@sglyon There's a very good reason to merge this PR:

Currently, when you define a constant in your own module which gets precompiled and which relies on an extension, the constant does not get the desired value. This is, because all functionality added via `Requires` is only available after execution of `__init__()`.
Here's a little MWE for demonstration:
```julia
module TestPlotlyBase

using JSON3
using PlotlyBase

const PL = JSON3.write(PlotlyBase.Layout())

function __init__()
    println(PL[1:100])
end

end
```
if you execute this module via `using` you will find that the JSON3 conversion went wrong.
```julia
julia> pushfirst!(LOAD_PATH, "./src")
julia> using TestPlotlyBase
{"fields":{"template":{"data":{"scatterpolargl":[{"fields":{"type":"scatterpolargl","marker":{"color
```
However, if you use @sjkelly 's PR you find the expected behaviour.
```julia
julia> pushfirst!(LOAD_PATH, "./src")
julia> using TestPlotlyBase
{"template":{"layout":{"coloraxis":{"colorbar":{"ticks":"","outlinewidth":0}},"xaxis":{"gridcolor":"
```
Finally, there are two corrections, I'd like to propose before releasing a new version:
- `json(Layout())` doesn't produce the correct result, the fix is `JSON.lower(a::HasFields) = _json_lower(a)` in sjson.jl instead of `JSON.lower(a::HasFields) = a.fields`
- Color conversion in ColorsExt should be `Colors.hex(a, :auto)` in order to force rgba format for colors with transparency.

I'd be happy to supply another PR to make these two fixes, ones this PR is merged. Just let me know.

**Comment by hhaensel** [comment]
One more point. Colors is automatically installed via ColorSchemes. Wouldn't it make sense to move the content of ColorsExt.jl to json.jl and just add `using ColorSchemes.Colors`

**Comment by hhaensel** [comment]
Finally, there are two methods implemented for setting the Project.toml for testing:
1) via [extras] and [target] in ./Project.toml
2) via Project.toml in ./test/ProjectToml and ./test/Manifest.toml

If implemented, method 2) wins.
Is this by purpose, maybe due to some compatibility issue?

**Comment by alyst** [comment]
I agree with @hhaensel, JSON support for *Colorant* types is not optional, it is required to support *ColorScheme* types. #107 makes *Colors.jl* a direct dependency.

**Pull request merged**
