### PR TITLE
support different numbers of columns in subplots

### PR DESCRIPTION
**Pull request by hhaensel**
This is the PR to #50

### CODE REVIEW

**Comment by hhaensel** [comment]
Hold on, needs still a small correction ...

**Comment by hhaensel** [comment]
Should be ok now 😃

**Comment by hhaensel** [comment]
@sglyon I saw that you released a new version. Just tested that this PR also works with the latest version. What do you think about this enhancement?

**Comment by sglyon** [comment]
Hey @hhaensel thank you for the work here!

I have been active working on some long overdue updates. I will put reviewing this PR on my list for this week. 

Thanks for contributing. You may also be interested in the new `Subplots` type and the `make_subplots` function in PlotlyJS.jl package.

**Comment by sglyon** [comment]
Whoa this is very cool!

I'm going to merge and tag right now

Thank you

**Pull request merged**
